force-app/main/default/objects/Answer_Row__c/Answer_Row__c.object-meta.xml
<CustomObject>
    <label>Answer Row</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Answer Row Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer_Row__c/fields/Answer_Row_Location__c.field-meta.xml
<CustomField>
    <fullName>Answer_Row_Location__c</fullName>
    <label>Answer Row Location</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer_Row__c/fields/Answer_Row_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Row_Text__c</fullName>
    <label>Answer Row Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer_Row__c/fields/Crossword__c.field-meta.xml
<CustomField>
    <fullName>Crossword__c</fullName>
    <label>Crossword</label>
    <referenceTo>Crossword__c</referenceTo>
    <relationshipLabel>Answer Rows</relationshipLabel>
    <relationshipName>Answer_Row</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Crossword__c/Crossword__c.object-meta.xml
<CustomObject>
    <label>Crossword</label>
    <nameField>
        <label>Crossword Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crosswords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crossword_Clue_Answer_Pair__c/Crossword_Clue_Answer_Pair__c.object-meta.xml
<CustomObject>
    <label>Crossword Clue-Answer Pair</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Clue-Answer Pair Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clue-Answer Pairs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Crossword_Clue_Answer_Pair__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Crossword_Clue_Answer_Pair__c/fields/Answer_ID__c.field-meta.xml
<CustomField>
    <fullName>Answer_ID__c</fullName>
    <label>Answer ID</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Crossword_Clue_Answer_Pair__c/fields/Answer_Row__c.field-meta.xml
<CustomField>
    <fullName>Answer_Row__c</fullName>
    <label>Answer Row</label>
    <referenceTo>Answer_Row__c</referenceTo>
    <relationshipLabel>Clue-Answer Pairs</relationshipLabel>
    <relationshipName>Crossword_Clue_Answer_Pair</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Crossword_Clue_Answer_Pair__c/fields/Crossword__c.field-meta.xml
<CustomField>
    <fullName>Crossword__c</fullName>
    <label>Crossword</label>
    <referenceTo>Crossword__c</referenceTo>
    <relationshipLabel>Clue-Answer Pairs</relationshipLabel>
    <relationshipName>Crossword_Clue_Answer_Pair</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Crossword_Clue_Answer_Pair__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Across</fullName>
            </value>
            <value>
                <fullName>Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CrosswordUploadFormController.cls
public with sharing class CrosswordUploadFormController {
  @AuraEnabled(cacheable=false)
  public static Id processCfpFileUpload(String uploadedCfpId) {
    Dom.XmlNode crossFire = getCrosswordAsXml(uploadedCfpId);

    String grid = crossFire.getChildElement('GRID', null).getText();
    grid = grid.removeStart('\n');

    String title = crossFire.getChildElement('TITLE', null).getText();

    Crossword__c crossword = upsertCrossword(grid, title);

    delete [SELECT Id FROM Answer_Row__c WHERE Crossword__c = :crossword.Id];

    List<Answer_Row__c> answerRowRecords = insertAnswerRowRecords(
      grid,
      crossword.Id
    );

    insertClueAnswerPairs(crossFire, answerRowRecords);

    return '';
  }

  private static Dom.XmlNode getCrosswordAsXml(String uploadedCfpId) {
    ContentVersion cfpFile = [
      SELECT VersionData
      FROM ContentVersion
      WHERE ContentDocumentId = :uploadedCfpId AND IsLatest = TRUE
    ];

    String data = cfpFile.VersionData.toString();

    Dom.Document domDocument = new Dom.Document();
    domDocument.load(data);

    Dom.XmlNode crossFire = domDocument.getRootElement();

    return crossFire;
  }

  private static Crossword__c upsertCrossword(String grid, String title) {
    Crossword__c crossword = new Crossword__c();

    List<Crossword__c> crosswords = [
      SELECT Id, Name
      FROM Crossword__c
      WHERE Name = :title
    ];

    if (!crosswords.isEmpty()) {
      crossword = crosswords[0];
    }

    crossword.Name = title;
    crossword.Size_Across__c = grid.indexOf('\n');
    crossword.Size_Top__c = grid.countMatches('\n');

    upsert crossword;

    return crossword;
  }

  private static List<Answer_Row__c> insertAnswerRowRecords(
    String grid,
    Id crosswordId
  ) {
    List<String> answerRows = grid.split('\n');

    List<Answer_Row__c> answerRowRecords = new List<Answer_Row__c>();

    Integer answerRowLocation = 1;

    for (String answerRow : answerRows) {
      List<String> answers = answerRow.split('\\.');

      Answer_Row__c answerRowRecord = new Answer_Row__c();
      answerRowRecord.Crossword__c = crosswordId;
      answerRowRecord.Answer_Row_Text__c = answerRow;
      answerRowRecord.Answer_Row_Location__c = answerRowLocation;

      answerRowRecords.add(answerRowRecord);

      answerRowLocation++;
    }

    insert answerRowRecords;

    return answerRowRecords;
  }

  private static void insertClueAnswerPairs(
    Dom.XmlNode crossFire,
    List<Answer_Row__c> answerRowRecords
  ) {
    List<Dom.XmlNode> clueNodes = crossFire.getChildElement('WORDS', null)
      .getChildElements();

    List<Crossword_Clue_Answer_Pair__c> clueAnswerPairs = new List<Crossword_Clue_Answer_Pair__c>();

    Integer answerId = 0;

    for (Answer_Row__c answerRowRecord : answerRowRecords) {
      List<String> answersWithBlanks = answerRowRecord.Answer_Row_Text__c.split(
        '\\.'
      );

      List<String> answers = new List<String>();

      for (String answer : answersWithBlanks) {
        if (!String.isBlank(answer)) {
          answers.add(answer);
        }
      }

      for (String answer : answers) {
        Crossword_Clue_Answer_Pair__c clueAnswerPair = new Crossword_Clue_Answer_Pair__c();

        Dom.XmlNode clueNode = clueNodes[answerId];

        clueAnswerPair.Answer_Row__c = answerRowRecord.Id;
        clueAnswerPair.Clue__c = clueNode.getText();
        clueAnswerPair.Answer__c = answer;
        clueAnswerPair.Direction__c = clueNode.getAttributeValue('dir', null);
        clueAnswerPair.Answer_ID__c = answerId;

        answerId++;

        clueAnswerPairs.add(clueAnswerPair);
      }
    }

    insert clueAnswerPairs;
  }
}