force-app/main/default/objects/Answer_Row__c/Answer_Row__c.object-meta.xml
<CustomObject>
    <label>Answer Row</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Answer Row Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer_Row__c/fields/Answer_Row_Location__c.field-meta.xml
<CustomField>
    <fullName>Answer_Row_Location__c</fullName>
    <label>Answer Row Location</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer_Row__c/fields/Answer_Row_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Row_Text__c</fullName>
    <label>Answer Row Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer_Row__c/fields/Puzzle__c.field-meta.xml
<CustomField>
    <fullName>Puzzle__c</fullName>
    <label>Puzzle</label>
    <referenceTo>Puzzle__c</referenceTo>
    <relationshipLabel>Answer Rows</relationshipLabel>
    <relationshipName>Answer_Row</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Puzzle__c/Puzzle__c.object-meta.xml
<CustomObject>
    <label>Puzzle</label>
    <nameField>
        <label>Puzzle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Puzzles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PuzzleController.cls
public with sharing class PuzzleController {
  @AuraEnabled(cacheable=true)
  public static String getAnswerRowDtos(Id puzzleId) {
    List<Answer_Row__c> answerRows = [
      SELECT Answer_Row_Text__c, Answer_Row_Location__c
      FROM Answer_Row__c
      WHERE Puzzle__c = :puzzleId
      ORDER BY Answer_Row_Location__c ASC
    ];

    List<AnswerRowDto> answerRowDtos = new List<AnswerRowDto>();

    for (Answer_Row__c answerRow : answerRows) {
      List<Square> squares = new List<Square>();

      String answerRowText = answerRow.Answer_Row_Text__c;

      for (
        Integer columnLocation = 0;
        columnLocation < answerRowText.length();
        columnLocation++
      ) {
        Integer characterCode = answerRowText.charAt(columnLocation);
        String currentCharacter = String.fromCharArray(
          new List<Integer>{ characterCode }
        );

        Square square = new Square();

        square.columnLocation = String.valueOf(columnLocation);
        square.squareText = currentCharacter;

        squares.add(square);
      }

      AnswerRowDto answerRowDto = new AnswerRowDto();

      answerRowDto.rowLocation = Integer.valueOf(
        answerRow.Answer_Row_Location__c
      );
      answerRowDto.squares = squares;

      answerRowDtos.add(answerRowDto);
    }

    return JSON.serialize(answerRowDtos);
  }

  @TestVisible
  private class AnswerRowDto {
    @TestVisible
    Integer rowLocation { get; set; }

    @TestVisible
    List<Square> squares { get; set; }
  }

  private class Square {
    String columnLocation { get; set; }
    String squareText { get; set; }
  }
}